// <auto-generated />
using System;
using CarFixFiler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarFixFiler.Migrations
{
    [DbContext(typeof(CarFixFilerContext))]
    [Migration("20260317112753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarFixFiler.Data.Car", b =>
                {
                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EngineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineDisplacement")
                        .HasColumnType("int");

                    b.Property<int>("ManufatureYear")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicensePlateNumber");

                    b.HasIndex("CustomerName");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("CarFixFiler.Data.Customer", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LaborCostDiscount")
                        .HasColumnType("int");

                    b.Property<int>("PartCostDiscount")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CarFixFiler.Data.Service", b =>
                {
                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicensePlateNumber", "Date");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CarFixFiler.Data.ServiceItem", b =>
                {
                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int");

                    b.HasKey("LicensePlateNumber", "Date", "ItemName");

                    b.ToTable("ServiceItems");
                });

            modelBuilder.Entity("CarFixFiler.Data.Car", b =>
                {
                    b.HasOne("CarFixFiler.Data.Customer", "Customer")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarFixFiler.Data.Service", b =>
                {
                    b.HasOne("CarFixFiler.Data.Car", "Car")
                        .WithMany("Services")
                        .HasForeignKey("LicensePlateNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarFixFiler.Data.ServiceItem", b =>
                {
                    b.HasOne("CarFixFiler.Data.Service", "Service")
                        .WithMany("ServiceItems")
                        .HasForeignKey("LicensePlateNumber", "Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CarFixFiler.Data.Car", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CarFixFiler.Data.Customer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarFixFiler.Data.Service", b =>
                {
                    b.Navigation("ServiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
